# Assets
asset_base: "/assets"
asset_version: "0.1.0"

# Build settings
markdown: "kramdown"
exclude:
  - "core"

# Collections
collections:
  examples:
    output: false

# Nav
nav:
  - text: "Examples"
    link: "#examples"
  - text: "Getting started"
    link: "#getting-started"
  - text: "GitHub"
    label: "See this project on Github.com"
    link: "//github.com/hankchizljaw/boilerform"